version: '3'
services:
  knowledge-base:
    build: ./knowledge-base
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db

  model:
    build: ./model
    ports:
      - "8001:8000"
    networks:
      - app-network
    depends_on:
      - db

  api-gateway:
    build: ./api-gateway
    ports:
      - "8002:8000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    build: ./db 
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  kpi-engine:
    build: ./kpi-engine
    ports:
      - "8003:8000" 
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

