version: '3'
services:
  knowledge-base:
    build: ./knowledge-base
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db

  model:
    build: ./model
    ports:
      - "8001:8000"
    networks:
      - app-network
    depends_on:
      - db

  api-gateway:
    build: ./api-gateway
    ports:
      - "8002:8000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    build: ./smart-industrial-database/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./smart-industrial-database/data:/var/lib/postgresql/data
    networks:
      - app-network
    container_name: smart-database-container

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5051:80"  
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  
      PGADMIN_DEFAULT_PASSWORD: password      
    networks:
      - app-network

  kpi-engine:
    build: ./kpi-engine/
    ports:
      - "8004:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

